export enum ConfirmPageSelectors {
  ConnectAction_CancelButton = 'ConfirmPage/ConnectAction/CancelButton',
  ConnectAction_RetryButton = 'ConfirmPage/ConnectAction/RetryButton',
  ConnectAction_ConnectButton = 'ConfirmPage/ConnectAction/ConnectButton',
  SignAction_RejectButton = 'ConfirmPage/SignAction/RejectButton',
  SignAction_SignButton = 'ConfirmPage/SignAction/SignButton',
  DecryptAction_RejectButton = 'ConfirmPage/DecryptAction/RejectButton',
  DecryptAction_AcceptButton = 'ConfirmPage/DecryptAction/AcceptButton',
  RecordsAction_RejectButton = 'ConfirmPage/RecordsAction/RejectButton',
  RecordsAction_AcceptButton = 'ConfirmPage/RecordsAction/AcceptButton',
  TransactionAction_RejectButton = 'ConfirmPage/TransactionAction/RejectButton',
  TransactionAction_AcceptButton = 'ConfirmPage/TransactionAction/AcceptButton',
  BulkTransactionsAction_RejectButton = 'ConfirmPage/BulkTransactionsAction/RejectButton',
  BulkTransactionsAction_AcceptButton = 'ConfirmPage/BulkTransactionsAction/AcceptButton',
  DeployAction_RejectButton = 'ConfirmPage/DeployAction/RejectButton',
  DeployAction_AcceptButton = 'ConfirmPage/DeployAction/AcceptButton',
  RequestPrivateNotes_RejectButton = 'ConfirmPage/RequestPrivateNotes/RejectButton',
  RequestPrivateNotes_AcceptButton = 'ConfirmPage/RequestPrivateNotes/AcceptButton',
  SignData_RejectButton = 'ConfirmPage/SignData/RejectButton',
  SignData_AcceptButton = 'ConfirmPage/SignData/AcceptButton',
  RequestAssets_RejectButton = 'ConfirmPage/RequestAssets/RejectButton',
  RequestAssets_AcceptButton = 'ConfirmPage/RequestAssets/AcceptButton',
  RequestImportPrivateNote_RejectButton = 'ConfirmPage/RequestImportPrivateNote/RejectButton',
  RequestImportPrivateNote_AcceptButton = 'ConfirmPage/RequestImportPrivateNote/AcceptButton'
}
